---
galaxy_info:
  author: Tutum Pro Team
  description: Deploy PostgreSQL database to Kubernetes for Tutum Engine
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Kubernetes
      versions:
        - all

dependencies:
  - role: kubernetes.core
