---
# k8s_tutum_engine - Deploy Tutum Engine to Kubernetes

- name: Include install tasks
  ansible.builtin.include_tasks: install.yml
  when: k8s_tutum_engine_state == 'present'

- name: Include uninstall tasks
  ansible.builtin.include_tasks: uninstall.yml
  when: k8s_tutum_engine_state == 'absent'
