---
galaxy_info:
  author: Tutum Pro Team
  description: Generate Tutum Platform Kubernetes installation files
  license: Proprietary
  min_ansible_version: "2.14"
  platforms:
    - name: Kubernetes
      versions:
        - all

dependencies: []
