---
# Tutum Admin CLI Installation Playbook (Docker)
#
# Usage:
#   ansible-playbook tutumpro.cicd.cli

- name: Install Tutum Admin CLI (Docker)
  hosts: all
  become: true
  roles:
    - role: tutumpro.cicd.docker.tutum_cli
