---
# Tutum Docker Plugin Installation Playbook
#
# Usage:
#   ansible-playbook tutum_pro.cicd.plugin

- name: Install Tutum Docker Plugin
  hosts: all
  become: true
  roles:
    - role: tutum_pro.cicd.docker.tutum_plugin
