---
# Tutum Version Report Playbook (Docker)
#
# Usage:
#   ansible-playbook tutum_pro.cicd.report

- name: Generate Tutum Version Report (Docker)
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: tutum_pro.cicd.docker.tutum_report
