---
# Tutum Version Report Playbook (Docker)
#
# Usage:
#   ansible-playbook tutumpro.cicd.report

- name: Generate Tutum Version Report (Docker)
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: tutumpro.cicd.docker.tutum_report
